<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_-60_search</name>
   <tag></tag>
   <elementGuidId>90fa508e-7ae8-4318-8355-e96c508f58c1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;search&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e2c075d9-cef2-4f92-8d76-7400b52e1447</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>492b5c52-7227-417f-9030-3e55d9df8da6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>902df32c-51af-4528-b2fe-ce7071d64e3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>search</value>
      <webElementGuid>4db6fd63-ff94-4878-ba4b-57ca217dd261</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>search-form__input ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>b2267530-35c4-49b5-b6b6-2e0179fd2dcf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Я шукаю...</value>
      <webElementGuid>c76b1c18-1045-4506-96b7-017e9d3cd2b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/div[@class=&quot;wrapper central-wrapper js-wrapper ng-star-inserted&quot;]/div[1]/rz-header[@class=&quot;app-header ng-star-inserted&quot;]/rz-main-header[@class=&quot;header--thin ng-star-inserted&quot;]/header[@class=&quot;header&quot;]/div[@class=&quot;layout&quot;]/div[@class=&quot;header-layout&quot;]/div[@class=&quot;header-search js-app-search-suggest&quot;]/form[@class=&quot;search-form ng-untouched ng-pristine ng-valid&quot;]/div[@class=&quot;search-form__inner&quot;]/div[@class=&quot;search-form__input-wrapper&quot;]/input[@class=&quot;search-form__input ng-untouched ng-pristine ng-valid&quot;]</value>
      <webElementGuid>19072372-d3d2-4238-97e4-edd414a6ed81</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='search']</value>
      <webElementGuid>206b5ef9-4a1f-49b2-8348-fcef72913e09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>6ed372ea-da0e-4bb8-b99b-00624fcba742</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'search' and @placeholder = 'Я шукаю...']</value>
      <webElementGuid>61c119b8-1cc6-4466-a4b3-7ddb11b69a43</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
