<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h1_Samsung</name>
   <tag></tag>
   <elementGuidId>78508842-edd3-43d9-9cc0-e2fc4a9e6365</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Повернись живим'])[1]/following::h1[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>h1.catalog-heading</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>9098adcb-e13d-4c26-8fa0-694a41b2adf7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>catalog-heading</value>
      <webElementGuid>17268246-03ad-41f5-b22d-8ba9b5628e03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Samsung</value>
      <webElementGuid>5a3d0a55-6fdf-4d87-97dc-c08aeb6b4291</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/div[@class=&quot;wrapper central-wrapper js-wrapper ng-star-inserted&quot;]/div[1]/rz-brand[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;central-wrapper&quot;]/main[1]/div[@class=&quot;layout&quot;]/div[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;catalog-header ng-star-inserted&quot;]/h1[@class=&quot;catalog-heading&quot;]</value>
      <webElementGuid>93d2ee76-5a0a-431e-999a-f8f2a4b69cdc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Повернись живим'])[1]/following::h1[1]</value>
      <webElementGuid>f1dd0bd0-78a4-479f-866c-d2e849cebe9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='UA'])[1]/following::h1[1]</value>
      <webElementGuid>1621d010-8d04-47dd-ab78-be7cbefb365b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='АКЦІЯ'])[1]/preceding::h1[1]</value>
      <webElementGuid>33dae6a9-a15c-42d8-948f-0ac610f91ec0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Мобільний телефон Samsung Galaxy S23 Ultra 12/512GB Phantom Black (SM-S918BZKHSEK)'])[1]/preceding::h1[1]</value>
      <webElementGuid>59b1e590-da3f-4763-85c5-e1af76f6dbc7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Samsung']/parent::*</value>
      <webElementGuid>d33b8da3-54c7-4b53-b530-302b52b3e763</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1</value>
      <webElementGuid>33519761-26c2-4e59-ab99-524a5696c872</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[(text() = 'Samsung' or . = 'Samsung')]</value>
      <webElementGuid>3d484245-afab-49e5-9faf-82fd263d9214</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
